### ISSUE TITLE
JMX_INSTANCE_NAME not part of EntityDefinition

### ISSUE THREAD

**Issue by mvillarejo** [tradel/AppDynamicsREST#15]
Hello,

I"m getting this exception whilst getting get_healthrule_violations:

`
_type must be one of [ACCOUNT, AGENT_CONFIGURATION, ALL, APPLICATION, APPLICATION_COMPONENT, APPLICATION_COMPONENT_NODE, APPLICATION_DIAGNOSTIC_DATA, AUTOMATIC_LEAK_DETECTION, BACKEND, BACKEND_DISCOVERY_CONFIG, BUSINESS_TRANSACTION, BUSINESS_TRANSACTION_GROUP, CALL_GRAPH_CONFIGURATION, CUSTOM_EXIT_POINT_DEFINITION, CUSTOM_MATCH_POINT_DEFINITION, CUSTOM_MEMORY_STRUCTURE, DASHBOARD, ERROR, ERROR_CONFIGURATION, DOT_NET_ERROR_CONFIGURATION, PHP_ERROR_CONFIGURATION, EUM_CONFIGURATION, EVENT, GLOBAL_CONFIGURATION, INCIDENT, JMX_CONFIG, MACHINE_INSTANCE, MEMORY_CONFIGURATION, NOTIFICATION_CONFIG, OBJECT_INSTANCE_TRACKING, POLICY, RULE, SQL_DATA_GATHERER_CONFIG, STACK_TRACE, THREAD_TASK, TRANSACTION_MATCH_POINT_CONFIG, USER, GROUP, ACCOUNT_ROLE, WORKFLOW, WORKFLOW_EXCUTION, POJO_DATA_GATHERER_CONFIG, HTTP_REQUEST_DATA_GATHERER_CONFIG, BASE_PAGE, IFRAME, AJAX_REQUEST] but got JMX_INSTANCE_NAME
` 

is it missing from the entity in `appd/model/entity_def.py`?

cheers,

**Comment by tradel** [comment]
I'm sorry, I am no longer with AppDynamics, and this project is no longer being maintained. Please feel free to fork the project and work on it yourself! Thanks.

**Comment by mvillarejo** [comment]
Any chance you can grant me access to upload new versions to PYPi?

`Submitting dist/AppDynamicsREST-0.4.6.tar.gz to https://pypi.python.org/pypi
Upload failed (403): You are not allowed to edit 'AppDynamicsREST' package information
error: Upload failed (403): You are not allowed to edit 'AppDynamicsREST' package information
make: *** [release] Error 1`

thanks
