### ISSUE TITLE
release new versions to pypi

### ISSUE THREAD

**Issue by mvillarejo** [tradel/AppDynamicsREST#16]
hello,

now that you're no longer supporting this library, would you mind sharing permissions to push new versions to pypi? it might help other people.

cheers,

**Comment by tradel** [comment]
Hi @mvillarejo. I am reaching out to AppDynamics to see if they want to take this over as an official project. If not, I would be happy to hand it over to anyone who's interested in maintaining.

**Comment by tradel** [comment]
It appears AppDynamics is not interested in maintaining this package. If you can send me your PyPI username, I will make you a maintainer.

**Comment by mvillarejo** [comment]
All right! here we go: **mvillarejo**

**Comment by tradel** [comment]
I've added you as a maintainer. Thanks for stepping up to do this!
