### ISSUE TITLE
URL in repo title is parked

### ISSUE THREAD

**Issue by erikthered** [tradel/AppDynamicsREST#2]
Maybe have it point to here? http://community.appdynamics.com/t5/eXchange-Community-AppDynamics/Python-SDK-for-Controller-REST-API/idi-p/917

**Comment by tradel** [comment]
Where do you see a URL in the repo title? The title is just "AppDynamicsREST".

**Comment by erikthered** [comment]
I think description is what I meant. It looks like the URL is fine now (I think it was a different URL before).

**Comment by tradel** [comment]
Thanks Erik. They were revamping our Community site a few weeks ago and a few pages temporarily went missing. Maybe that was what you saw.
