### ISSUE TITLE
Encrypt Pypi password

### ISSUE THREAD

**Issue by eliluminado** [tradel/AppDynamicsREST#5]
Encrypted Pypi password in .travis.yml

http://docs.travis-ci.com/user/encryption-keys/

**Comment by tradel** [comment]
Encryption added in 2d0c0db866768c22b875ace73fc3e547b7e65181 and password changed in 001f831238a738aac35c99ebb30b6688625e313f.

The funny thing is, I had already fixed this locally, just hadn't pushed to github yet. Thanks for the reminder.
