### ISSUE TITLE
base_url inconsistent

### ISSUE THREAD

**Issue by stillmatic** [tradel/AppDynamicsREST#6]
let's say I have an AppDynamics installation @ `https://example.com/`

when i define my AppDynamicsClient with `base_url = https://example.com` I can get data for applications, business transactions, servers, and tiers. 

but this `base_url` becomes problematic when trying to call `get_metric_tree`. in order to properly make calls to `get_metric_tree`, i need to instead say `base_url = https://example.com/controller/rest`. 

i'm not sure if this is a quirk of my particular installation, or if it's a bug in the python library.

**Comment by tradel** [comment]
I'm sorry, I am no longer with AppDynamics, and this project is no longer being maintained. Please feel free to fork the project and work on it yourself! Thanks.
